name: Pull Request Workflow

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Test
    uses: monta-app/github-workflows/.github/workflows/pull-request.yaml@5fe725f615503876677c1cd178a53644691ee84f
    with:
      gradle-module: core
    secrets:
      GHL_USERNAME: ${{ secrets.GHL_USERNAME }}
      GHL_PASSWORD: ${{ secrets.GHL_PASSWORD }}
  static-code-analysis:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Run detekt
        uses: monta-app/detekt-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
